master:
  enableXmlConfig: true
  serviceType: NodePort
  adminPassword: "oKNItqC34ndZYvkOYXybGcMOmab7tc2b"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hostName: jenkins.capstone.com
    tls:
    - secretName: tls-cert
      hosts:
      - jenkins.capstone.com
  httpsKeyStore:
    enable: true
    password: "password"
    jenkinsKeyStoreBase64Encoded:|
      /u3+7QAAAAIAAAABAAAAAgATY2Fwc3RvbmVwcm9qZWN0LmNvbQAAAXOh+2VdAAVYLjUwOQAABikw
      ggYlMIIEDaADAgECAhRaMMWzucA5DPZ3GlmLQ0MMYPdLVTANBgkqhkiG9w0BAQsFADCBoTELMAkG
      A1UEBhMCQ0ExEDAOBgNVBAgMB09udGFyaW8xEDAOBgNVBAcMB1Rvcm9udG8xGTAXBgNVBAoMEENh
      cHN0b25lIFByb2plY3QxCzAJBgNVBAsMAklUMRwwGgYDVQQDDBNjYXBzdG9uZXByb2plY3QuY29t
      MSgwJgYJKoZIhvcNAQkBFhlhZG1pbkBjYXBzdG9uZXByb2plY3QuY29tMB4XDTIwMDcyNTE1MTMz
      OFoXDTIzMDUxNTE1MTMzOFowgaExCzAJBgNVBAYTAkNBMRAwDgYDVQQIDAdPbnRhcmlvMRAwDgYD
      VQQHDAdUb3JvbnRvMRkwFwYDVQQKDBBDYXBzdG9uZSBQcm9qZWN0MQswCQYDVQQLDAJJVDEcMBoG
      A1UEAwwTY2Fwc3RvbmVwcm9qZWN0LmNvbTEoMCYGCSqGSIb3DQEJARYZYWRtaW5AY2Fwc3RvbmVw
      cm9qZWN0LmNvbTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANKYhv5n4GR3OXKLbDzM
      t4VlydUydhyPbLn2UT70QTb8yuqpNnMWDATZ9ok32DpuYutANxFxj0TQEfSaPjSZ8oyxxaxVv7z3
      EkH2GVLwi47D7YDygHp0lpuCb8WshHoEBADMNjvjmcX30gKcmuhziXj11aYJaoLsBtzXTSwQ5ZBb
      TyQMTpHAF0OQFjBo3e3DUYWeFrth12H97mYHYCYjCCKEFqQA15x9REnPvBLEFA+2d2LOwb78ecYN
      sqKAKpoVq7t5tbrMEeIgjSN/gxrufaGKrQY0FZacNCyiA6zulDw4triH1XWVNOmX7WzOigZCp6GJ
      wY4hQqtejImEYiyAwiX/MXn6kjM69DpflGidSGgl1Iv/vkc7XrnTJcPJPVFk/Jdz2uqUwre8EbO6
      e3AofomoCmtGS1xjJaBxs6sbe6IkpQMiOXaoXkrweRbKpXvhPQswb/T9Vo+CJYkeayWNWxz2Met4
      Alob5oJZRbpfEuvACikCzG62x5t42lC0U8GESQK3laQxFujuEJRDdk6y3WeFhvgneK+3Bpzv+2Au
      rzOXCJPpd3ylFX0+H4MPiOnal+3PIyFfcn9FSdpPHDPY7yKJ8+2eipzTsO4NMkNk+TtkgUGKY9Pb
      4LM42IaizFZsOA3G2t2s9zQTM1gd0zIl0rwqG0sS+lGpxx7YhHW+GK25AgMBAAGjUzBRMB0GA1Ud
      DgQWBBT10iLDK6AmOaVOa2qnSl/brIJYszAfBgNVHSMEGDAWgBT10iLDK6AmOaVOa2qnSl/brIJY
      szAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQCBxYxVtxxNldJ4ORKqoPwLq/nZ
      jRFrAikASwGV79gfOTzq8YOisMCPcxGTud8ZDCusr8Kze5fgXIdBHy5y8My9tx2LcP8mifGeMl1o
      4fjIelqyxEzeO8xMUkrc9Ipld4kZjChHTYduOEAQAOrKwI6Xwf8L9x2TSDcgBSYlbT7H3G2NVByx
      W2oyqlRIEwjQGs9ZHKl+Lpm4N5se84Ush2HD5Bdw3QKXGE//zHfeRjLPi6sn9kRU8h2g17wsK+0x
      fINuVWnv/xCz6tRxcdufoJ5JpBBavDIJC6/tZtlNyWNspATbCJZ7P+m2+5zKxcKeHrw3kN2+hL59
      DLf/Y9ssFqCq/CBu2dKSk1efqxPu1N0ANknUqcH5sf7okgoByC/u5aGi/IROvIafWosCp85/P2Ti
      Du1FI81e5GO4nAyRYK3zG9g7DnUx3mR/TbkU7VZXpmdBsj70F6aqlSC0m1HpihHaPprLHNotsow2
      oxZlMiwv/TnPeg13JqkR22Bjwwy0yC/2rF0wHa1nQlzqaedLFBp/ZaPjb8pw0PSgW5+wYIDB/ZLz
      ZlXPcxpH/S0EV435CLLn+U4tWN+hFYlMbkPlraMNVN1nnBKhpZZKTBYGG1803PShaWgtf2mlvdAC
      Mgkyh6DapUGhv5DCB7H2H0oLtMgF1aWZuq5nhFIDNgX/MXTiDalYdvnbigY1pjT02PNZlr2rMRyI