master:
  slaveJenkinsUrl: http://jenkins.capstone.com
  serviceType: NodePort
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hostName: jenkins.capstone.com
